development:
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  reconnect: false
  database: tenacity_dev
  pool: 5
  username: <%= ENV['DB_USER_DEV'] %>
  password: <%= ENV['DB_PWD_DEV'] %>
  host: 127.0.0.1
  port: 3306

test:
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  reconnect: false
  database: tenacity_test
  pool: 5
  username: <%= ENV['DB_USER_TEST'] %>
  password: <%= ENV['DB_PWD_TEST'] %>
  host: 127.0.0.1
  port: 3306

production:
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  reconnect: false
  database: tenacity
  pool: 5
  username: <%= ENV['DB_USER_PROD'] %>
  password: <%= ENV['DB_PWD_PROD'] %>
  host: <%= ENV['DB_HOST_PROD'] %>
  port: 3306
  #sslca: /home/deploy/certs/rds-combined-ca-bundle.pem
